FROM golang:1.9

ADD . /go/src/github.com/Sharykhin/go-users-grpc/server

WORKDIR /go/src/github.com/Sharykhin/go-users-grpc/server

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

RUN dep ensure && \
    go get github.com/canthefason/go-watcher && \
    go install github.com/canthefason/go-watcher/cmd/watcher

ENTRYPOINT watcher

EXPOSE 50051