// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	CreateUserRequest
	UpdateUserRequest
	UserResponse
	UserListReponse
	UserID
	Empty
	CountResponse
	QueryCriteria
	CountCriteria
	UserFilter
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Activated bool   `protobuf:"varint,3,opt,name=activated" json:"activated,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

type UpdateUserRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	// Types that are valid to be assigned to Name:
	//	*UpdateUserRequest_NameNull
	//	*UpdateUserRequest_NameValue
	Name isUpdateUserRequest_Name `protobuf_oneof:"name"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isUpdateUserRequest_Name interface {
	isUpdateUserRequest_Name()
}

type UpdateUserRequest_NameNull struct {
	NameNull bool `protobuf:"varint,2,opt,name=name_null,json=nameNull,oneof"`
}
type UpdateUserRequest_NameValue struct {
	NameValue string `protobuf:"bytes,3,opt,name=name_value,json=nameValue,oneof"`
}

func (*UpdateUserRequest_NameNull) isUpdateUserRequest_Name()  {}
func (*UpdateUserRequest_NameValue) isUpdateUserRequest_Name() {}

func (m *UpdateUserRequest) GetName() isUpdateUserRequest_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UpdateUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateUserRequest) GetNameNull() bool {
	if x, ok := m.GetName().(*UpdateUserRequest_NameNull); ok {
		return x.NameNull
	}
	return false
}

func (m *UpdateUserRequest) GetNameValue() string {
	if x, ok := m.GetName().(*UpdateUserRequest_NameValue); ok {
		return x.NameValue
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateUserRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpdateUserRequest_OneofMarshaler, _UpdateUserRequest_OneofUnmarshaler, _UpdateUserRequest_OneofSizer, []interface{}{
		(*UpdateUserRequest_NameNull)(nil),
		(*UpdateUserRequest_NameValue)(nil),
	}
}

func _UpdateUserRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateUserRequest)
	// name
	switch x := m.Name.(type) {
	case *UpdateUserRequest_NameNull:
		t := uint64(0)
		if x.NameNull {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *UpdateUserRequest_NameValue:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.NameValue)
	case nil:
	default:
		return fmt.Errorf("UpdateUserRequest.Name has unexpected type %T", x)
	}
	return nil
}

func _UpdateUserRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateUserRequest)
	switch tag {
	case 2: // name.name_null
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Name = &UpdateUserRequest_NameNull{x != 0}
		return true, err
	case 3: // name.name_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Name = &UpdateUserRequest_NameValue{x}
		return true, err
	default:
		return false, nil
	}
}

func _UpdateUserRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpdateUserRequest)
	// name
	switch x := m.Name.(type) {
	case *UpdateUserRequest_NameNull:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += 1
	case *UpdateUserRequest_NameValue:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.NameValue)))
		n += len(x.NameValue)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UserResponse struct {
	ID        string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Activated bool   `protobuf:"varint,4,opt,name=activated" json:"activated,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	DeletedAt string `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt" json:"deleted_at,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

func (m *UserResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UserResponse) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type UserListReponse struct {
	Users []*UserResponse `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *UserListReponse) Reset()                    { *m = UserListReponse{} }
func (m *UserListReponse) String() string            { return proto.CompactTextString(m) }
func (*UserListReponse) ProtoMessage()               {}
func (*UserListReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserListReponse) GetUsers() []*UserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserID struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *UserID) Reset()                    { *m = UserID{} }
func (m *UserID) String() string            { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()               {}
func (*UserID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CountResponse struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *CountResponse) Reset()                    { *m = CountResponse{} }
func (m *CountResponse) String() string            { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()               {}
func (*CountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryCriteria struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *QueryCriteria) Reset()                    { *m = QueryCriteria{} }
func (m *QueryCriteria) String() string            { return proto.CompactTextString(m) }
func (*QueryCriteria) ProtoMessage()               {}
func (*QueryCriteria) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryCriteria) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *QueryCriteria) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CountCriteria struct {
	Criteria []*QueryCriteria `protobuf:"bytes,1,rep,name=criteria" json:"criteria,omitempty"`
}

func (m *CountCriteria) Reset()                    { *m = CountCriteria{} }
func (m *CountCriteria) String() string            { return proto.CompactTextString(m) }
func (*CountCriteria) ProtoMessage()               {}
func (*CountCriteria) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CountCriteria) GetCriteria() []*QueryCriteria {
	if m != nil {
		return m.Criteria
	}
	return nil
}

type UserFilter struct {
	Limit    int64            `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset   int64            `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Criteria []*QueryCriteria `protobuf:"bytes,3,rep,name=criteria" json:"criteria,omitempty"`
}

func (m *UserFilter) Reset()                    { *m = UserFilter{} }
func (m *UserFilter) String() string            { return proto.CompactTextString(m) }
func (*UserFilter) ProtoMessage()               {}
func (*UserFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserFilter) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UserFilter) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UserFilter) GetCriteria() []*QueryCriteria {
	if m != nil {
		return m.Criteria
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*UserListReponse)(nil), "user.UserListReponse")
	proto.RegisterType((*UserID)(nil), "user.UserID")
	proto.RegisterType((*Empty)(nil), "user.Empty")
	proto.RegisterType((*CountResponse)(nil), "user.CountResponse")
	proto.RegisterType((*QueryCriteria)(nil), "user.QueryCriteria")
	proto.RegisterType((*CountCriteria)(nil), "user.CountCriteria")
	proto.RegisterType((*UserFilter)(nil), "user.UserFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	List(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserListReponse, error)
	Count(ctx context.Context, in *CountCriteria, opts ...grpc.CallOption) (*CountResponse, error)
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Empty, error)
	Remove(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Empty, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) List(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserListReponse, error) {
	out := new(UserListReponse)
	err := grpc.Invoke(ctx, "/user.User/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Count(ctx context.Context, in *CountCriteria, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := grpc.Invoke(ctx, "/user.User/Count", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := grpc.Invoke(ctx, "/user.User/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/user.User/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Remove(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/user.User/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	List(context.Context, *UserFilter) (*UserListReponse, error)
	Count(context.Context, *CountCriteria) (*CountResponse, error)
	Create(context.Context, *CreateUserRequest) (*UserResponse, error)
	Update(context.Context, *UpdateUserRequest) (*Empty, error)
	Remove(context.Context, *UserID) (*Empty, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).List(ctx, req.(*UserFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountCriteria)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Count(ctx, req.(*CountCriteria))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Remove(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _User_List_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _User_Count_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _User_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _User_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _User_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5b, 0x6b, 0x13, 0x51,
	0x10, 0xde, 0xbb, 0xd9, 0x69, 0xab, 0xed, 0x58, 0x75, 0x09, 0x16, 0xc3, 0x81, 0x42, 0x9e, 0xaa,
	0xb6, 0x0f, 0x7d, 0xf0, 0xc5, 0x9a, 0x28, 0x0d, 0x88, 0xe0, 0x81, 0xfa, 0xe2, 0x43, 0x59, 0x93,
	0x29, 0x2c, 0xd9, 0xcd, 0xc6, 0x73, 0xce, 0x06, 0xf2, 0xe6, 0x8f, 0xf1, 0x87, 0xca, 0xb9, 0xe4,
	0xb6, 0xad, 0xd0, 0xb7, 0x99, 0x6f, 0x2e, 0xdf, 0x7c, 0x33, 0x0c, 0x40, 0x23, 0x49, 0x9c, 0xcd,
	0x45, 0xad, 0x6a, 0x8c, 0xb4, 0xcd, 0x7e, 0xc2, 0xd1, 0x40, 0x50, 0xae, 0xe8, 0x46, 0x92, 0xe0,
	0xf4, 0xbb, 0x21, 0xa9, 0x10, 0x21, 0x9a, 0xe5, 0x15, 0x65, 0x7e, 0xcf, 0xef, 0xa7, 0xdc, 0xd8,
	0x78, 0x0c, 0x31, 0x55, 0x79, 0x51, 0x66, 0x81, 0x01, 0xad, 0x83, 0xaf, 0x21, 0xcd, 0xc7, 0xaa,
	0x58, 0xe4, 0x8a, 0x26, 0x59, 0xd8, 0xf3, 0xfb, 0x1d, 0xbe, 0x01, 0xd8, 0x14, 0x8e, 0x6e, 0xe6,
	0x93, 0x56, 0xf3, 0xa7, 0x10, 0x8c, 0x86, 0xae, 0x75, 0x30, 0x1a, 0xe2, 0x09, 0xa4, 0x9a, 0xe0,
	0x76, 0xd6, 0x94, 0xb6, 0x79, 0xe7, 0xda, 0xe3, 0x1d, 0x0d, 0x7d, 0x6b, 0xca, 0x12, 0xdf, 0x00,
	0x98, 0xf0, 0x22, 0x2f, 0x1b, 0x32, 0x14, 0xe9, 0xb5, 0xc7, 0x4d, 0xc9, 0x0f, 0x0d, 0x7d, 0x4a,
	0xec, 0xb0, 0xec, 0xaf, 0x0f, 0xfb, 0x96, 0x47, 0xce, 0xeb, 0x99, 0xa4, 0x7b, 0x44, 0x2b, 0x55,
	0xc1, 0x43, 0xaa, 0xc2, 0xff, 0xaa, 0x8a, 0x5a, 0xaa, 0xf0, 0x04, 0x60, 0x6c, 0x56, 0x36, 0xb9,
	0xcd, 0x55, 0x16, 0x9b, 0xc2, 0xd4, 0x21, 0x57, 0x4a, 0x87, 0x27, 0x54, 0x92, 0x0b, 0x27, 0x36,
	0xec, 0x90, 0x2b, 0xc5, 0x3e, 0xc0, 0x33, 0x3d, 0xe5, 0xd7, 0x42, 0x2a, 0x4e, 0x76, 0xd0, 0x3e,
	0xc4, 0xfa, 0x16, 0x32, 0xf3, 0x7b, 0x61, 0x7f, 0xef, 0x1c, 0xcf, 0xcc, 0x95, 0xb6, 0xb5, 0x70,
	0x9b, 0xc0, 0x32, 0x48, 0x34, 0x3c, 0x1a, 0xb6, 0xc5, 0xb1, 0x27, 0x10, 0x7f, 0xae, 0xe6, 0x6a,
	0xc9, 0x4e, 0xe1, 0x60, 0x50, 0x37, 0x33, 0xb5, 0x5e, 0xc3, 0x31, 0xc4, 0x63, 0x0d, 0x98, 0xe4,
	0x90, 0x5b, 0x87, 0x5d, 0xc2, 0xc1, 0xf7, 0x86, 0xc4, 0x72, 0x20, 0x0a, 0x45, 0xa2, 0xc8, 0xf1,
	0x10, 0xc2, 0x29, 0x2d, 0x5d, 0x47, 0x6d, 0xea, 0x42, 0xbb, 0x74, 0x77, 0x71, 0xe3, 0xb0, 0x8f,
	0xae, 0xff, 0xba, 0xf0, 0x2d, 0x74, 0xc6, 0xce, 0x76, 0x02, 0x9e, 0x5b, 0x01, 0x3b, 0xfd, 0xf9,
	0x3a, 0x89, 0x4d, 0x01, 0xb4, 0x88, 0x2f, 0x45, 0xa9, 0x48, 0x68, 0x96, 0xb2, 0xa8, 0x8a, 0xf5,
	0x78, 0xc6, 0xc1, 0x97, 0x90, 0xd4, 0x77, 0x77, 0x92, 0x94, 0x21, 0x0f, 0xb9, 0xf3, 0x76, 0xc8,
	0xc2, 0x47, 0x90, 0x9d, 0xff, 0x09, 0x20, 0xd2, 0x6c, 0xf8, 0x1e, 0x22, 0xbd, 0x73, 0x3c, 0xdc,
	0x6c, 0xd7, 0x4e, 0xd0, 0x7d, 0xb1, 0x41, 0xb6, 0xae, 0xc2, 0x3c, 0xbc, 0x80, 0xd8, 0x48, 0x45,
	0xc7, 0xb1, 0xa3, 0xbb, 0xbb, 0x0d, 0xae, 0x96, 0xcd, 0x3c, 0xbc, 0x84, 0xc4, 0x3e, 0x14, 0xbe,
	0x72, 0x09, 0xed, 0xf7, 0xea, 0x3e, 0x70, 0x60, 0xe6, 0xe1, 0x3b, 0x48, 0xec, 0xb3, 0xac, 0x0a,
	0xef, 0xbd, 0x4e, 0x77, 0xcf, 0x06, 0xec, 0xa1, 0x3d, 0x3c, 0x85, 0x84, 0x53, 0x55, 0x2f, 0x08,
	0xf7, 0x37, 0x1d, 0x47, 0xc3, 0x56, 0xda, 0xaf, 0xc4, 0xfc, 0xfb, 0xc5, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x65, 0x24, 0x38, 0xe4, 0xfd, 0x03, 0x00, 0x00,
}
